name: CI
on:
  - push
  - pull_request
jobs:
  continuous-integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - run: make unit_test
      - run: make integration_test
      - run: make
      - run: ls dist/