name: CI
on:
  - push
  - pull_request
jobs:
  continuous-integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - run: make unit_test
      - run: make integration_test
      - run: make build
      - run: make package TAG="${{github.ref_name}}"
      - name: Login DockerHub si ref version
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ctalec
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push si ref
        if: startsWith(github.ref, 'refs/tags/')
        run: make release  TAG="${{github.ref_name}}"
      - name: Login DockerHub si branche main
        uses: docker/login-action@v3
        if: contains('refs/heads/main', github.ref)
        with:
          username: ctalec
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push si branche main
        if: contains('refs/heads/main', github.ref)
        run: make release  TAG="${{github.ref_name}}"
      - run: ls dist/
